import Image from "next/image";
import { FC } from "react";

interface RevolvingGridProps {}

const RevolvingGrid: FC<RevolvingGridProps> = ({}) => {
  // Inspiration: https://preline.co/ && https://www.algoexpert.io/product
  const lightItem = `w-full object-cover shadow-lg rounded-lg dark:shadow-gray-900/[.75] dark:hidden`;
  const darkItem = `hidden w-full object-cover shadow-lg rounded-lg dark:shadow-gray-900/[.75] dark:block`;

  return (
    <div
      className="absolute w-full h-screen overflow-hidden rounded-lg -z-30"
      style={{ perspective: "700px" }}
    >
      <div
        style={{
          transform:
            "translate3d(7%, -2%, 0px) scale3d(0.9, 0.8, 1) rotateX(15deg) rotateY(-9deg) rotateZ(32deg)",
        }}
        className="shadow-2xl grid grid-cols-3 gap-12 w-[60rem] sm:w-[80rem] lg:w-[50rem] h-[55rem] md:h-[90rem] lg:h-[75rem] overflow-hidden origin-[50%_0%]"
      >
        <div className="grid gap-9 w-full h-[440px] animate-sliding-img-up-1">
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
        </div>
        <div className="grid gap-9 w-full h-[440px] animate-sliding-img-down-1">
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
        </div>
        <div className="grid gap-9 w-full h-[440px] animate-sliding-img-up-2">
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-6.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"	https://preline.co/assets/svg/visuals-dark/hero-card-11.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={lightItem}
          />
          <Image
            src={"https://preline.co/assets/svg/visuals-dark/hero-card-14.svg"}
            alt={"stuff"}
            width={100}
            height={100}
            className={darkItem}
          />
        </div>
      </div>
    </div>
  );
};

export default RevolvingGrid;
